version: '3'

services:
  pgsql:
    container_name: pgsql
    image: postgres:alpine
    expose:
      - '5432'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=knex_test

  node-app:
      container_name: node16-app
      image: node:16
      depends_on: 
        - pgsql
      ports: 
        - "3000:3000"
      volumes: 
        - .:/app
      working_dir: /app 
      command: bash -c "sleep 11 && npm i && npx knex migrate:latest && npx knex seed:run && npm run start:dev " 
      environment: 
        - NODE_ENV=development

volumes:
  pg-data: