version: '3'

services:
  pgsql:
    image: postgres:alpine
    expose:
      - '5432'
    ports:
      - '5432:5432'
    container_name: 'pgsql_image'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: knex_test

 
volumes:
  pg-data:
